name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html==3.2.0 

      - name: Run tests
        run: pytest --tb=short --html=pytest_report.html

      - name: Check PEP8 compliance
        run: |
          pip install flake8
          flake8 word_sentence_counter.py --max-line-length=100
